services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:  todo_db
      
    
    ports:
     - "3306:3306"
    networks:
     - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      -  db
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: todo_db
       DB_HOST: db 
    networks:
      -  app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    networks:
      - app-network 

    depends_on:
      -  backend

networks:
  app-network:
    driver: bridge












